<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Financial Reports</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; font-family: Arial, sans-serif; }
        .container { width: 1200px; margin: 50px auto; display: flex; gap: 30px; }
        .sidebar { width: 220px; border-right: 1px solid #e0e0e0; padding-right: 20px; }
        .sidebar h3 { margin-bottom: 20px; color: #333; }
        .sidebar a { display: block; margin: 12px 0; color: #0066cc; text-decoration: none; padding: 8px 0; }
        .sidebar a:hover { text-decoration: underline; }
        .content { flex: 1; }
        .content h2 { margin-bottom: 25px; color: #333; }
        table { width: 90%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ccc; padding: 12px 15px; text-align: left; }
        th { background: #f5f5f5; color: #333; }
        tr:hover { background: #fafafa; }
        a { color: #0066cc; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .no-report { margin-top: 20px; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <h3>Welcome, {{ $this->getLoggedInUser()->Name }}!</h3>
            <a href="{{ route('upmuser.dashboard') }}">Home</a>
            <a href="{{ route('upmuser.dashboard') }}">Make Donation</a>
            <a href="{{ route('upmuser.report_list') }}">View Financial Reports</a>
            <a href="{{ route('login') }}">Logout</a>
        </div>

        <div class="content">
            <h2>Published Financial Reports</h2>
            @if($reports->isEmpty())
                <p class="no-report">No published reports available.</p>
            @else
                <table>
                    <tr>
                        <<th>Report Period</</th>
                        <<th>Generated By (Manager ID)</</th>
                        <<th>Action</</th>
                    </tr>
                    @foreach($reports as $report)
                    <tr>
                        <td>{{ $report->start_date }} ~ {{ $report->end_date }}</td>
                        <td>{{ $report->generated_by }}</td>
                        <td><a href="{{ route('upmuser.report_details', $report->report_ID) }}">View Report</a></td>
                    </tr>
                    @endforeach
                </table>
            @endif
        </div>
    </div>
</body>
</html>