<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $report->start_date }} ~ {{ $report->end_date }} Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; font-family: Arial, sans-serif; }
        .container { width: 1200px; margin: 50px auto; display: flex; gap: 30px; }
        .sidebar { width: 220px; border-right: 1px solid #e0e0e0; padding-right: 20px; }
        .sidebar h3 { margin-bottom: 20px; color: #333; }
        .sidebar a { display: block; margin: 12px 0; color: #0066cc; text-decoration: none; padding: 8px 0; }
        .sidebar a:hover { text-decoration: underline; }
        .content { flex: 1; }
        .content h2 { margin-bottom: 10px; color: #333; }
        .content p.subtitle { margin-bottom: 25px; color: #666; }
        .summary { margin: 25px 0; padding: 15px; border: 1px solid #e0e0e0; border-radius: 4px; width: 90%; }
        .summary p { margin: 8px 0; color: #555; }
        .summary strong { color: #333; }
        h3 { margin: 30px 0 15px; color: #333; }
        table { width: 90%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ccc; padding: 12px 15px; text-align: left; }
        th { background: #f5f5f5; color: #333; }
        tr:hover { background: #fafafa; }
        .no-data { margin-top: 15px; color: #666; }
        .back-btn { display: inline-block; margin-top: 20px; padding: 10px 20px; background: #0066cc; color: white; border-radius: 4px; text-decoration: none; }
        .back-btn:hover { background: #0052aa; }
    </style>
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <h3>Welcome, {{ $this->getLoggedInUser()->Name }}!</h3>
            <a href="{{ route('upmuser.dashboard') }}">Home</a>
            <a href="{{ route('upmuser.dashboard') }}">Make Donation</a>
            <a href="{{ route('upmuser.report_list') }}">View Financial Reports</a>
            <a href="{{ route('login') }}">Logout</a>
        </div>

        <div class="content">
            <h2>{{ $report->start_date }} ~ {{ $report->end_date }} Financial Report</h2>
            <p class="subtitle">Generated by Manager (ID: {{ $report->generated_by }})</p>

            <!-- 报告核心财务数据（匹配文档 2.3.11.3 UI） -->
            <div class="summary">
                <p><strong>Opening Balance:</strong> RM {{ number_format($report->opening_balance, 2) }}</p>
                <p><strong>Total Donations:</strong> RM {{ number_format($report->total_donation, 2) }}</p>
                <p><strong>Total Expenses:</strong> RM {{ number_format($report->total_expense, 2) }}</p>
                <p><strong>Closing Balance:</strong> RM {{ number_format($report->closing_balance, 2) }}</p>
            </div>

            <!-- 捐款明细 -->
            <h3>Donation Details</h3>
            @if($donations->isEmpty())
                <p class="no-data">No donations in this period.</p>
            @else
                <table>
                    <tr>
                        <<th>Donation ID</</th>
                        <<th>Donor ID</</th>
                        <<th>Amount (RM)</</th>
                        <<th>Date</</th>
                    </tr>
                    @foreach($donations as $don)
                    <tr>
                        <td>{{ $don->Donation_ID }}</td>
                        <td>{{ $don->Donor_User_ID }}</td>
                        <td>{{ number_format($don->Amount, 2) }}</td>
                        <td>{{ $don->Donated_Date }}</td>
                    </tr>
                    @endforeach
                </table>
            @endif

            <a href="{{ route('upmuser.report_list') }}" class="back-btn">Back to Report List</a>
        </div>
    </div>
</body>
</html>